services:
  students-api:
    build: .
    restart: on-failure
    ports:
      - "8081:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/students_app/app
      - ./migrations:/students_app/migrations
      - ./tests:/students_app/tests
      - ./config.py:/students_app/config.py
      - ./run.py:/students_app/run.py
    environment:
      DATABASE_URI: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-data: