services:
  students-api:
    build: .
    restart: on-failure
    ports:
      - "8081:5000"
    volumes:
      - ./app:/students_app/app
      - ./migrations:/students_app/migrations
      - ./tests:/students_app/tests
      - ./config.py:/students_app/config.py
      - ./run.py:/students_app/run.py
    environment:
      DATABASE_URI: $DATABASE_URI