services:
  students-api-1:
    build: .
    restart: on-failure
    ports:
      - "8081:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./students_log:/students_log
    environment:
      DATABASE_URI: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}"

  students-api-2:
    build: .
    restart: on-failure
    ports:
      - "8082:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./students_log:/students_log
    environment:
      DATABASE_URI: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}"
    

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx-lb:
    image: nginx
    ports:
    - "8080:80"
    depends_on:
    - students-api-1
    - students-api-2
    volumes:
    - ./nginx-config/load-balancer.conf:/etc/nginx/conf.d/load-balancer.conf

    
volumes:
  mysql-data: