---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-students-app-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chfrchko5/students-api-proj.git
    path: helm_chart
    targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: True
      selfHeal: True
    syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-observ-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chfrchko5/students-api-proj.git
    path: helm_chart_observ
    targetRevision: dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: True
      selfHeal: True
    syncOptions:
    - CreateNamespace=true