---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: observ
  labels:
    app: blackbox-exporter-service
spec:
  selector:
    app: blackbox-exporter
  ports:
  - name: blackbox-metrics
    port: 9115
    targetPort: 9115
    protocol: TCP