apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter-metrics
  namespace: observ
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: blackbox-exporter-service
  endpoints:
  - port: blackbox-metrics
    path: /probe
    interval: 15s
    params:
      module:
      - http_prober
      - tcp_prober
    static_configs:
    - targets:
      - http://api-app-service.students-api.svc.cluster.local:5000/healthcheck
      - http://db-service.students-api.svc.cluster.local:3306
    relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: blackbox-exporter.observ.svc.cluster.local:9115