name: build and push docker image

on:
    push:
        branches:
            - main
        paths:
            - 'app/**'
            - 'migrations/**'
            - 'tests/**'
            - '**.py'
            - 'Dockerfile'
            - 'entrypoint.sh'
            - 'requirements.txt'
    
    workflow_dispatch:

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: checkout the repo
              uses: actions/checkout@v4
            
            - name: lint the dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile
            
            - name: via Makefile install and run ruff python linter
              run: make ruff-install && make ruff-run
    
    build-and-push:
        runs-on: ubuntu-latest
        permissions: write-all
        needs: lint-and-test
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: build and push docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: chfrchko7/students-api:0.5.5