name: build and push docker image

on:
    push:
        branches:
            - main
        paths:
            - 'app/**'
            - 'migrations/**'
            - 'tests/**'
            - '**.py'
            - 'Dockerfile'
            - 'entrypoint.sh'
            - 'requirements.txt'
    
    workflow_dispatch:

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        permissions: write-all
        
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4
            
            - name: lint the dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile
            
            - name: via Makefile install and run ruff python linter
              run: make ruff-install && make ruff-run
    
    build-and-push:
        runs-on: ubuntu-latest
        needs: lint-and-test
        steps:
            - name: checkout the repo
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: set up tagging
              id: tag
              uses: mathieudutour/github-tag-action@v6.2
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                default_bump: patch

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: docker login
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: build the docker image with auto-incremented tag
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/students-api:${{ steps.tag.outputs.new_tag }} .
                docker push ${{ secrets.DOCKER_USERNAME }}/students-api:${{ steps.tag.outputs.new_tag }}